import Foundation

extension MLBTeam {
    static let orioles = MLBTeam(code: 110, name: "Orioles", location: "Baltimore", abbreviation: "BAL", division: .east, league: .american)
    static let redsox = MLBTeam(code: 111, name: "Red Sox", location: "Boston", abbreviation: "BOS", division: .east, league: .american)
    static let yankees = MLBTeam(code: 147, name: "Yankees", location: "New York", abbreviation: "NYY", division: .east, league: .american)
    static let bayrays = MLBTeam(code: 139, name: "Bay Rays", location: "Tampa", abbreviation: "TB", division: .east, league: .american)
    static let bluejays = MLBTeam(code: 141, name: "Blue Jays", location: "Toronto", abbreviation: "TOR", division: .east, league: .american)
    static let whitesox = MLBTeam(code: 145, name: "White Sox", location: "Chicago", abbreviation: "CHW", division: .central, league: .american)
    static let guardians = MLBTeam(code: 114, name: "Guardians", location: "Cleveland", abbreviation: "CLE", division: .central, league: .american)
    static let tigers = MLBTeam(code: 116, name: "Tigers", location: "Detroit", abbreviation: "DET", division: .central, league: .american)
    static let royals = MLBTeam(code: 118, name: "Royals", location: "Kansas City", abbreviation: "KAN", division: .central, league: .american)
    static let twins = MLBTeam(code: 142, name: "Twins", location: "Minnesota", abbreviation: "MIN", division: .central, league: .american)
    static let astros = MLBTeam(code: 117, name: "Astros", location: "Houston", abbreviation: "HOU", division: .west, league: .american)
    static let angels = MLBTeam(code: 108, name: "Angels", location: "Los Angeles", abbreviation: "LAA", division: .west, league: .american)
    static let athletics = MLBTeam(code: 133, name: "Athletics", location: "Oakland", abbreviation: "OAK", division: .west, league: .american)
    static let mariners = MLBTeam(code: 136, name: "Mariners", location: "Seattle", abbreviation: "SEA", division: .west, league: .american)
    static let rangers = MLBTeam(code: 140, name: "Rangers", location: "Texas", abbreviation: "TEX", division: .west, league: .american)
    static let braves = MLBTeam(code: 144, name: "Braves", location: "Atlanta", abbreviation: "ATL", division: .east, league: .national)
    static let marlins = MLBTeam(code: 146, name: "Malins", location: "Miami", abbreviation: "MIA", division: .east, league: .national)
    static let mets = MLBTeam(code: 121, name: "Mets", location: "New York", abbreviation: "NYM", division: .east, league: .national)
    static let phillies = MLBTeam(code: 143, name: "Phillies", location: "Philadelphia", abbreviation: "PHI", division: .east, league: .national)
    static let nationals = MLBTeam(code: 120, name: "Nationals", location: "Washington", abbreviation: "WAS", division: .east, league: .national)
    static let cubs = MLBTeam(code: 112, name: "Cubs", location: "Chicago", abbreviation: "CHC", division: .central, league: .national)
    static let reds = MLBTeam(code: 113, name: "Reds", location: "Cincinnati", abbreviation: "CIN", division: .central, league: .national)
    static let brewers = MLBTeam(code: 158, name: "Brewers", location: "Milwaukee", abbreviation: "MIL", division: .central, league: .national)
    static let pirates = MLBTeam(code: 134, name: "Pirates", location: "Pittsburgh", abbreviation: "PIT", division: .central, league: .national)
    static let cardinals = MLBTeam(code: 138, name: "Cardinals", location: "St. Louis", abbreviation: "STL", division: .central, league: .national)
    static let diamondbacks = MLBTeam(code: 109, name: "Diamondbacks", location: "Arizona", abbreviation: "ARI", division: .west, league: .national)
    static let dodgers = MLBTeam(code: 119, name: "Dodgers", location: "Los Angeles", abbreviation: "LAD", division: .west, league: .national)
    static let rockies = MLBTeam(code: 115, name: "Rockies", location: "Colorado", abbreviation: "COL", division: .west, league: .national)
    static let padres = MLBTeam(code: 135, name: "Padres", location: "San Diego", abbreviation: "SD", division: .west, league: .national)
    static let giants = MLBTeam(code: 137, name: "Giants", location: "San Francisco", abbreviation: "SF", division: .west, league: .national)
}
